[RunParameters]
n_jobs = 2
tries_per_task = 1
evaluator = "browseruse"

[Falco]
headless = true
use_vision = true
model = "openai/gpt-4o"
max_steps = 20
history_type = "short_observations_with_short_data"
