[RunParameters]
n_jobs = 2
tries_per_task = 1
evaluator = "browseruse"

[Falco]
headless = false
use_vision = false
model = "cerebras/llama-3.3-70b"
max_steps = 20
history_type = "short_observations_with_short_data"
